# Use the Python 3.8.1 image
FROM python:3.8.1-slim-buster

# Set the working directory to /usr/src/mast
WORKDIR /usr/src/mast

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


# Install system dependencies
RUN apt-get update && apt-get install -y netcat

# Install Python dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt /usr/src/mast/requirements.txt
RUN pip install -r requirements.txt

# Copy the current directory contents into the container at /usr/src/mast
COPY . /usr/src/mast

RUN ls
RUN pwd

# Run entrypoint.sh
ENTRYPOINT ["/usr/src/mast/entrypoint.sh"]
